### PR TITLE
allow setting archive mode to always

### PR DESCRIPTION
**Pull request by saz**
As `archive_mode` is currently set based on the value of `archiver`, it's not possible to set it to `always`.

I've added a new parameter `force_archive_mode` to set it explicitly to `on`, `off`, or `always`.

This avoids a backwards-incompatible change

### CODE REVIEW

**Comment by deric** [comment]
Looks good, thanks!

**Comment by saz** [comment]
@deric Any chance for a new release to the forge?

**Comment by deric** [comment]
Sure, if you're done with patches :slightly_smiling_face:

**Comment by saz** [comment]
For right now, yes :) everything's working for me

**Comment by deric** [comment]
Released as [v4.1.0](https://github.com/deric/puppet-barman/releases/tag/v4.1.0).

**Pull request merged**
