### PR TITLE
Fix templates

### PR DESCRIPTION
**Pull request by raredemon**
add group to templates/logrotate.conf.erb
add configuration_files_directory to templates/barman.conf.erb

### CODE REVIEW

**Comment by deric** [comment]
Thanks!

**Comment by deric** [comment]
@raredemon Having two config directories is a bit confusing, don't you think?
```
/etc/barman/barman.conf
/etc/barman.d/
```
maybe more common approach would be:
```
/etc/barman.conf
/etc/barman.d/
```
or
```
/etc/barman/barman.conf
/etc/barman/conf.d/
```

**Comment by raredemon** [comment]
@deric just made as I use it. may be directory layout isn't correct for all barman users and it will be worthwhile to make directories as variable?

**Comment by deric** [comment]
Yes, that would be useful :+1:

**Pull request merged**
