### PR TITLE
Bump minimum and maximum module version requirements 

### PR DESCRIPTION
**Pull request by shamil**
This PR allows to use the module with newer versions of module dependencies. 
All the tests are passes as intended.

### CODE REVIEW

**Comment by shamil** [comment]
@deric can you please take a look at this PR, we run it in our production and it works well. Would be nice if you can release a new version.

**Comment by deric** [comment]
Looks good, thanks!

**Comment by shamil** [comment]
Thanks for quick merge @deric 
Can you also publish the version to Puppet forge?

**Comment by deric** [comment]
Yes, I can't really test it right now, but it's tagged and released.

**Pull request merged**
